openwisp_notifications/urls.py
from django.urls import include, path

from . import views
from .api.urls import get_api_urls
from .views import notification_preference_view, unsubscribe_view

app_name = "notifications"


def get_urls(api_views=None, social_views=None):
    """
    Returns a list of urlpatterns
    Arguments:
        api_views(optional): views for Notifications API
    """
    urls = [
        path(
            "notifications/resend-verification-email/",
            views.resend_verification_email,
            name="resend_verification_email",
        ),
        path("api/v1/notifications/", include(get_api_urls(api_views))),
        path(
            "notifications/preferences/",
            notification_preference_view,
            name="notification_preference",
        ),
        path(
            "notifications/user/<uuid:pk>/preferences/",
            notification_preference_view,
            name="user_notification_preference",
        ),
        path("notifications/unsubscribe/", unsubscribe_view, name="unsubscribe"),
    ]
    return urls


app_name = "notifications"
urlpatterns = get_urls()

openwisp_notifications/templates/openwisp_notifications/preferences.html
{% extends "admin/base_site.html" %}

{% load i18n %}
{% load static %}

{% block title %}
  {% trans "Notification Preferences" %}
{% endblock title %}

{% block extrastyle %}
  {{ block.super }}
  <link rel="stylesheet" type="text/css" href="{% static 'openwisp-notifications/css/preferences.css' %}" />
{% endblock extrastyle %}

{% block breadcrumbs %}
  <div class="breadcrumbs">
    <a href="{% url 'admin:index' %}">{% trans 'Home' %}</a> &rsaquo;
    {% if username %}
      <a href="{% url 'admin:app_list' app_label='openwisp_users' %}">{% trans 'Users and Organizations' %}</a> &rsaquo;
      <a href="{% url 'admin:openwisp_users_user_changelist' %}">{% trans 'Users' %}</a> &rsaquo;
      <a href="{% url 'admin:openwisp_users_user_change' user_id %}">{{ username }}</a> &rsaquo;
    {% endif %}
    {% trans 'Notification Preferences' %}
  </div>
{% endblock breadcrumbs %}

{% block content %}
  <div class="settings-container" data-user-id="{{ user_id }}">
    <div class="loader"></div>
    <div class="global-settings">
      <h2>{% trans 'Global Settings' %}</h2>
      <div class="global-settings-container">
        <!-- Global Web Settings -->
        <div class="global-setting">
          <div class="global-setting-content">
            <div class="global-setting-text">
              <h2>
                <span class="icon icon-web"></span>
                {% trans 'Web' %}
              </h2>
              <p>
                {% trans 'Enable or disable all web notifications globally' %}.
              </p>
              <div class="global-setting-dropdown" data-web-state="No">
                <button class="global-setting-dropdown-toggle"></button>
                <div class="global-setting-dropdown-menu">
                  <button data-web-state="Yes">{% trans 'Notify on web' %}</button>
                  <button data-web-state="No">{% trans "Don't notify on web" %}</button>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- Global Email Settings -->
        <div class="global-setting">
          <div class="global-setting-content">
            <div class="global-setting-text">
              <h2>
                <span class="icon icon-email"></span>
                {% trans 'Email' %}
              </h2>
              <p>
                {% trans 'Enable or disable all email notifications globally' %}.
              </p>
              <div class="global-setting-dropdown" data-email-state="No">
                <button class="global-setting-dropdown-toggle"></button>
                <div class="global-setting-dropdown-menu">
                  <button data-email-state="Yes">{% trans 'Notify by email' %}</button>
                  <button data-email-state="No">{% trans "Don't notify by email" %}</button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Org Settings -->
    <div class="organizations">
      <div class="intro">
        <h2>
          {% trans 'Organization Settings' %}
        </h2>
        <p>
          {% trans 'Fine-tune notification settings for each organization below' %}.
        </p>
      </div>
      <div id="org-panels"></div>
    </div>
  </div>

  <!-- Confirmation Modal -->
  <div id="confirmation-modal" class="modal">
    <div class="modal-content">
      <div class="modal-header">
        <div class="modal-icon"></div>
        <h2></h2>
      </div>
      <p class="modal-message"></p>
      <div class="modal-buttons">
        <button class="button default" id="go-back">
          {% trans 'Go Back' %}
        </button>
        <button class="button default success-btn" id="confirm">
          {% trans 'Confirm' %}
        </button>
      </div>
    </div>
  </div>
{% endblock content %}

{% block footer %}
  {{ block.super }}
  {% if request.user.is_authenticated %}
    <script type="text/javascript" src="{% static 'openwisp-notifications/js/preferences.js' %}"></script>
  {% endif %}
{% endblock footer %}

openwisp_notifications/templates/openwisp_notifications/settings.html
{% extends "admin/base_site.html" %}

{% load i18n %}
{% load static %}

{% block title %}
  {% trans "Notification Preferences" %}
{% endblock %}

{% block extrastyle %}
  {{ block.super }}
  <link rel="stylesheet" type="text/css" href="{% static 'openwisp-notifications/css/settings.css' %}" />
{% endblock extrastyle %}

{% block breadcrumbs %}
  <div class="breadcrumbs">
    {% if request.user.id == user.id %}
      <a href="{% url 'admin:index' %}">{% trans 'Home' %}</a> &rsaquo;
    {% else %}
      <a href="{% url 'admin:index' %}">{% trans 'Home' %}</a> &rsaquo;
      <a href="{% url 'admin:app_list' app_label='openwisp_users' %}">{% trans 'Users and Organizations' %}</a> &rsaquo;
      <a href="{% url 'admin:openwisp_users_user_changelist' %}">{% trans 'Users' %}</a> &rsaquo;
      <a href="{% url 'admin:openwisp_users_user_change' user.id %}">{{ user.username }}</a> &rsaquo;
    {% endif %}
    {% trans 'Notification Preferences' %}
  </div>
{% endblock breadcrumbs %}

{% block pretitle %}Notification Preferences{% endblock %}

{% block content %}
  <div class="settings-container" data-user-id="{{ user.id }}">
    <div class="global-settings">
      <strong>Global Settings:</strong>
      <label>
        <input type="checkbox" id="global-web" />
        Web
      </label>
      <label>
        <input type="checkbox" id="global-email" />
        Email
      </label>
    </div>
    <div id="org-panels"></div>
  </div>
{% endblock content %}

{% block footer %}
  {{ block.super }}
  {% if request.user.is_authenticated %}
    <script type="text/javascript" src="{% static 'openwisp-notifications/js/settings.js' %}"></script>
  {% endif %}
{% endblock footer %}

openwisp_notifications/templates/openwisp_notifications/unsubscribe.html
{% extends 'account/base_entrance.html' %}
{% load i18n %}
{% load static %}

{% block title %}{% trans 'Manage Email Notifications' %}{% endblock %}

{% block extrastyle %}
  {{ block.super }}
  <link rel="stylesheet" type="text/css" href="{% static 'openwisp-notifications/css/unsubscribe.css' %}">
{% endblock %}

{% block menu-bar %}{% if user.is_authenticated %}{{ block.super }}{% endif %}{% endblock %}

{% block content %}
  <div class="unsubscribe-container">
    {% comment %} Workaround to use the same logo as webapp to make overriding easier. {% endcomment %}
    <div class="no-auth">
      <div id="site-name">
        <a class="logo"></a>
      </div>
    </div>
    <div class="unsubscribe-content">
      <div class="email-icon-container">
        <img class="email-icon"
             src="{% static "ui/openwisp/images/email.png" %}"
             alt="{% trans 'Email Icon' %}">
      </div>
      <h1>{% trans 'Email Notifications' %}</h1>
      {% if valid %}
        <div id="manage-preferences">
          <div class="status-msg-container">
            <p id="subscribed-message" class="{% if not is_subscribed %}hidden{% endif %}">
              {% trans 'You are currently subscribed to email notifications.' %}
            </p>
            <p id="unsubscribed-message" class="{% if is_subscribed %}hidden{% endif %}">
              {% trans 'You are currently unsubscribed from email notifications.' %}
            </p>
          </div>
          <div class="confirmation-msg-container hidden">
            <p id="confirm-subscribed" class="confirmation-msg hidden">
              {% trans 'Successfully subscribed to all email notifications.' %}
            </p>
            <p id="confirm-unsubscribed" class="confirmation-msg hidden">
              {% trans 'Successfully unsubscribed from all email notifications.' %}
            </p>
          </div>
          <button
            id="toggle-btn"
            class="button"
            data-has-subscribe="{{ is_subscribed|yesno:'true,false' }}"
          >
            {% if is_subscribed %}
              {% trans 'Unsubscribe' %}
            {% else %}
              {% trans 'Subscribe' %}
            {% endif %}
          </button>
        </div>
        <div id="error-msg-container" class="hidden">
          <p id="error-msg" class="error-msg">
            {% trans 'An error occurred while updating your notification preferences.' %}<br>
            {% trans 'You can update your preferences by ' %}
            <a href="{% url 'notifications:notification_preference' %}">
              {% trans 'logging into your account.' %}
            </a>
          </p>
        </div>
      {% else %}
        <div id="invalid-token-msg-container">
          <h2>{% trans 'Invalid or Expired Link' %}</h2>
          <p>{% trans 'The link you used is invalid or expired.' %}</p>
        </div>
      {% endif %}

      <div class="footer">
        <p>
          {% url 'notifications:notification_preference' as notification_preference_url %}
          {% blocktrans with url=notification_preference_url %}
            Fine-tune your alert settings in the
            <a href="{{ url }}" class="highlighted">notification preferences</a>.
          {% endblocktrans %}
        </p>
      </div>
    </div>
  </div>
{% endblock %}

{% block footer %}
  {{ block.super }}
  <script src="{% static 'openwisp-notifications/js/unsubscribe.js' %}"></script>
{% endblock %}